customerapp/urls.py
from django.contrib import admin
from django.urls import path

import customerapp.views as customerapp

app_name = 'customerapp'

urlpatterns = [

]

mainapp/urls.py
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('service/', mainapp.service, name='service'),
    path('team/', mainapp.team, name='team'),
    path('order/', mainapp.order, name='order')
]

mind_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'), name='mainapp'),
    path('customer', include('customerapp.urls'), name='customerapp'),
]

customerapp/models.py
from django.db import models


class Customer(models.Model):
    FAVORITE_MESSENGER = [
        ('VK', 'vk'),
        ('WA', 'WhatsApp'),
        ('VB', 'Viber'),
        ('TG', 'Telegram'),
        ('IG', 'Instagram'),
    ]
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=240, blank=True)
    favorite_messenger = models.CharField(max_length=2, choices=FAVORITE_MESSENGER, blank=True)
    is_active = models.BooleanField(default=True)
    date_add = models.DateTimeField(auto_now_add=True)
    date_born = models.DateField(blank=True)

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

mainapp/models.py
import requests
from django.db import models

#
# from customerapp.models import Customer
#
#
# class TypeSite(models.Model):
#     name = models.CharField(max_length=120)
#     description = models.TextField()
#     price = models.IntegerField(blank=True)
#     is_active = models.BooleanField(default=True)
#
#     class Meta:
#         verbose_name = 'тип сайта'
#         verbose_name_plural = 'типы сайтов'
#
#     def __str__(self):
#         return self.name


#
#
# class Order(models.Model):
#     STATUS = [
#         ('W', 'на рассмотрении'),
#         ('C', 'на согласовании'),
#         ('P', 'создание прототипа'),
#         ('D', 'создание дизайна'),
#         ('L', 'верстка'),
#         ('B', 'программирование'),
#         ('S', 'деплой'),
#         ('F', 'выполнен')
#     ]
#     owner = models.ForeignKey(to=Customer, on_delete=models.CASCADE)
#     name_site = models.CharField(max_length=240, blank=True)
#     description = models.TextField(blank=True)
#     date_create = models.DateTimeField(auto_now_add=True)
#     date_update_status = models.DateTimeField(auto_now=True)
#     status = models.CharField(max_length=1, choices=STATUS, default='W')
#     type_site = models.ForeignKey(to=TypeSite, on_delete=models.CASCADE)
#
#     class Meta:
#         verbose_name = 'заказ'
#         verbose_name_plural = 'заказы'
#
#     def __str__(self):
#         return self.name_site
from django.db.models.signals import post_save
from django.dispatch import receiver

from tmp import TOKEN, CHANNEL_ID


class Order(models.Model):
    Type_site = [
        ('L', 'Лединг'),
        ('V', 'сайт-визитка'),
        ('C', 'корпоративный сайт'),
        ('N', 'неопределен'),
    ]
    name = models.CharField(max_length=120)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=240, blank=True)
    type_site = models.CharField(max_length=1, choices=Type_site, default='N')
    time_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return self.name

@receiver(post_save, sender=Order)
def send_message(sender, **kwargs):
    message = f'пришел заказ {kwargs["instance"].name} {kwargs["instance"].phone} {kwargs["instance"].email}'
    send_to_telegram(message)


def send_to_telegram(message):
    token = TOKEN
    url = "https://api.telegram.org/bot"
    channel_id = CHANNEL_ID
    url += token
    method = url + "/sendMessage"

    r = requests.post(method, data={
        "chat_id": channel_id,
        "text": message
    })

    if r.status_code != 200:
        raise Exception("post_text error")

mainapp/forms.py
from django.forms import ModelForm

from mainapp.models import Order


class CreateOrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ('name', 'phone', 'email')

customerapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/views.py
from json import loads

from django.http import JsonResponse
from django.shortcuts import render

from mainapp.models import Order


def index(request):
    """
    main page
    """
    title = 'главная'
    content = {
        "title": title,
    }
    return render(request, 'mainapp/index.html', context=content)


def service(request):
    """
    service page
    """
    title = 'MindWeb - услуги'
    content = {
        "title": title,
    }
    return render(request, 'mainapp/service.html', context=content)


def team(request):
    """
    team page
    """
    title = 'MindWeb - команда'
    content = {
        "title": title,
    }
    return render(request, 'mainapp/team.html', context=content)


def order(request):
    if request.method == 'POST':
        try:
            date = loads(request.body.decode('utf-8'))
            Order.objects.create(name=date["name"], email=date["email"], phone=date["phone"])
            return JsonResponse({
                'status': 'ok',
                'code': 200
            })
        except Exception as e:
            # TODO  логирование
            print(e)
            return JsonResponse({
                'status': 'error',
                'code': 500
            })

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    {% block css %}
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link
                href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700&family=Nunito:wght@300;400;600&display=swap"
                rel="stylesheet"
        />
        <link rel="stylesheet" href="{% static 'css/general.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/queries.css' %}"/>

        <link
                rel="stylesheet"
                href="https://unpkg.com/swiper/swiper-bundle.min.css"
        />

    {% endblock %}

    {% block js %}
        <script src="{% static 'js/sidebar.js' %}" defer></script>
        <script src="{% static 'js/swiperForTablet.js' %}" defer></script>
        <script src="{% static 'js/menu.js' %}" defer></script>
        <script src="{% static 'js/formValidator.js' %}" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.8.0/gsap.min.js"></script>
    {% endblock %}

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <title>MindWeb</title>
</head>
{% block conteiner %}
{% endblock %}
</html>

mainapp/templates/mainapp/includes/inc__footer.html
{% load static %}

<footer class="container footer">
    <div class="flex footer-section">
        <h2 class="h2-footer">Мы всегда рады сотрудничеству!</h2>
        <p class="text-footer" id="test">
            Заполните, пожалуйста, форму и мы свяжемся с вами в ближайшее время!
        </p>
        <!-- <form action="#" 
        class="flex footer-form" name="main" method="post" id="formConnect"
              enctype="multipart/form-data"> -->
              <form name="main" class="flex footer-form" onsubmit="return fetchpost()" id="formConnect">
            {% csrf_token %}
            <input type="hidden" id="urlForm" value="{% url 'mainapp:order' %}">
            <input
                    type="text"
                    name="name"
                    id="name"
                    placeholder="Имя"
                    class="input-form timeline-form"
            />
            <div class="form--input--block timeline-form">
                <input
                        type="tel"
                        name="phone"
                        id="phone"
                        placeholder="Телефон"
                        class="input-form"
                />
            </div>
            <div class="form--input--block timeline-form">
                <input
                        type="email"
                        name="email"
                        id="email"
                        placeholder="E-mail"
                        class="input-form"
                />
            </div>
{#            <input#}
{#                    type="text"#}
{#                    name="website_type"#}
{#                    id="website_type"#}
{#                    placeholder="Тип сайта"#}
{#                    class="input-form timeline-form"#}
{#            />#}

            <label for="policy" class="label-form timeline-form">
                <input type="checkbox" name="policy" id="policy" required/>
                <span
                >Я подтверждаю согласие на обработку персональных данных в
            соответствии с условиями
            <span class="policy-span">Политики конфиденциальности</span></span
                >
            </label>

            <button type="submit" class="button-form timeline-form" id="submitButton">
                Отправить
            </button>
        </form>
        <div class="form-messagesent messSent" id="messSent">
            <p class="p-message">Ваша заявка отправлена.</p>
            <p class="p-message">Спасибо! Мы скоро свяжемся с вами.</p>
        </div>
        <div class="form-messagesent messNotSent" id="messNotSent">
            <p class="p-message">Что-то пошло не так</p>
            <p class="p-message">попробуйте отправить позже</p>
        </div>
    </div>
    <div class="grid footer-info grid-mobil-footer">
        <div class="flex footer-info-contact">
            <p>+7 911 402 43 89</p>
            <p>info@mind-web.ru</p>
        </div>
        <nav>
            <ul class="flex footer-info-menu">

                <li><a href="{% url 'mainapp:team' %}" class="footer-link">О нас.</a> </li>
                <li><a href="{% url 'mainapp:service' %}" class="footer-link">Тарифы.</a> </li>
                <li><a href="#" class="footer-link">Политика конфиденциальности.</a></li>
            </ul>
        </nav>
        <div class="flex footer-social-media">
            <img
                    src="{% static 'img/telegram.svg' %}"
                    class="icon-social-media"
                    alt="telegram icon"
            />
            <img
                    src="{% static 'img/vkontakte.svg' %}"
                    class="icon-social-media"
                    alt="vkontakte icon"
            />
        </div>
    </div>
</footer>

mainapp/templates/mainapp/includes/inc__header.html
{% load static %}

    <header class="flex header {% if request.resolver_match.url_name == 'index' %} header-absolute {% else %} black-bgr {% endif %} ">
        <nav class="main-nav">
            <ul class="flex main-nav-list">
                <li>
                    <a href="{% url 'mainapp:index' %}">
                        <img class="logo" alt="MindWeb logo" src="{% static 'img/logo.svg' %}"/>
                    </a>
                </li>
                <li class="main-nav-list-li">
                    <a class="main-nav-link" href="{% url 'mainapp:index' %}#services">
                        Услуги.
                        <svg viewBox="0 0 104 52" fill="none" class="svg svg-main-menu">
                            <path
                                    class="path"
                                    d="M42.5 7C42.5 7 15.9999 6 6.99996 12.5C-1.99999 19 1.99999 29.5 3.99997 33.5C5.99994 37.5 9.49997 45 24.5 49C39.5 53 62.5 51 72.9999 49C83.4999 47 92.9999 46.5 99.4999 37.5C106 28.5 103 21.5 91.9999 15C80.9999 8.5 74.3412 7.78516 62.5 5C52.1239 2.55946 35.5 1 35.5 1"
                            />
                        </svg>
                    </a>
                </li>
                <li class="main-nav-list-li">
                    <a class="main-nav-link" href="{% url 'mainapp:index' %}#projects">
                        Проекты.
                        <svg viewBox="0 0 104 52" fill="none" class="svg svg-main-menu-big">
                            <path
                                    class="path"
                                    d="M42.5 7C42.5 7 15.9999 6 6.99996 12.5C-1.99999 19 1.99999 29.5 3.99997 33.5C5.99994 37.5 9.49997 45 24.5 49C39.5 53 62.5 51 72.9999 49C83.4999 47 92.9999 46.5 99.4999 37.5C106 28.5 103 21.5 91.9999 15C80.9999 8.5 74.3412 7.78516 62.5 5C52.1239 2.55946 35.5 1 35.5 1"
                            />
                        </svg>
                    </a>
                </li>
            </ul>
        </nav>

        <div class="flex main-nav-list">
            <button class="btn-nav hide">Связаться с нами</button>
            <div class="flex burger-menu-block openNav" id="openNav">
                <div class="burger-menu openNav">&nbsp;</div>
            </div>
        </div>
    </header>
    <div id="mySidenav" class="sidenav">
        <ul id="myDropdown" class="flex menu__list">
            <li id="closeNav" class="closebtn accent-font closeNav">&times;</li>
            <li class="sidenav-link-mobil">
                <a href="{% url 'mainapp:service' %}" class="sidenav-link main-nav-link">
                    Услуги.
                </a>
            </li>
            <li class="sidenav-link-mobil">
                <a href="#" class="sidenav-link main-nav-link">
                    Проекты.
                </a>
            </li>
            <li>
                <a href="{% url 'mainapp:team' %}" class="sidenav-link main-nav-link">
                    О нас.
                    <svg viewBox="0 0 104 52" fill="none" class="svg svg-sidenav">
                        <path
                                class="path"
                                d="M42.5 7C42.5 7 15.9999 6 6.99996 12.5C-1.99999 19 1.99999 29.5 3.99997 33.5C5.99994 37.5 9.49997 45 24.5 49C39.5 53 62.5 51 72.9999 49C83.4999 47 92.9999 46.5 99.4999 37.5C106 28.5 103 21.5 91.9999 15C80.9999 8.5 74.3412 7.78516 62.5 5C52.1239 2.55946 35.5 1 35.5 1"
                        />
                    </svg>
                </a>
            </li>
            <li>
                <a href="{% url 'mainapp:service' %}" class="main-nav-link sidenav-link ">
                    Тарифы.
                    <svg viewBox="0 0 104 52" fill="none" class="svg svg-sidenav-long">
                        <path
                                class="path"
                                d="M42.5 7C42.5 7 15.9999 6 6.99996 12.5C-1.99999 19 1.99999 29.5 3.99997 33.5C5.99994 37.5 9.49997 45 24.5 49C39.5 53 62.5 51 72.9999 49C83.4999 47 92.9999 46.5 99.4999 37.5C106 28.5 103 21.5 91.9999 15C80.9999 8.5 74.3412 7.78516 62.5 5C52.1239 2.55946 35.5 1 35.5 1"
                        />
                    </svg>
                </a>
            </li>
        </ul>
        <div class="flex menu__list menu__list-mobil">
            <div class="main-nav-list-mobil hide-desctop">
                <button class="btn-nav">Связаться с нами</button>
            </div>
            <p class="sidenav-contact">+7 911 402 43 89</p>
            <p class="sidenav-contact">info@mind-web.ru</p>
            <div class="flex sidenav-social-media">
                <img src="{% static 'img/telegram.svg' %}" alt="telegram-icon">
                <img src="{% static 'img/instagram.svg' %}" alt="instagram-icon">
            </div>
        </div>
    </div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %} {% load static %} {% block conteiner %}

<body>
  <section class="section-hero bgr-img-cover">
    {% include 'mainapp/includes/inc__header.html' %}

    <div class="flex hero">
      <h1 class="heading-primary">
        Мы создаем уникальные <br />и функциональные сайты
      </h1>
      <h1 class="heading-primary-mobile">
        Мы создаем уникальные&nbsp;и функциональные <br />
        сайты
      </h1>
    </div>
  </section>
  <main>
    <h2 class="container h2 h2-section" id="services">Наши услуги.</h2>
    <!-- menu desctop -->
    <section class="menu-desctop">
      <div class="menu-fonts grid--menu">
        <div></div>
        <div
          class="container menu--content link1 bgr-img-cover grid grid--menu"
          data-id="link1"
        >
          <div class="flex flex-menu">
            <h2 class="h2 h2-menu">Сайты под ключ</h2>
            <p class="menu-p" data-id="0">Индивидуальная разработка сайта</p>
            <p class="menu-p" data-id="0">
              Адаптивные сайты на любых устройствах
            </p>
            <p class="menu-p" data-id="0">
              Исследование бизнеса, <br />конкурентов и целевой аудитории
            </p>
            <p class="menu-p" data-id="0">
              Наполнение контентом <br />(фото, товары, статьи и т.п.)
            </p>
            <div
              class="flex accent-font menu-accent-content menu-p"
              data-id="0"
            >
              <div class="menu-content one">Лендинг</div>
              <p class="menu-content-hide one-hide">
                <span class="bold">Лендинг</span>-это особый тип сайтов,
                оптимизированных для побуждения к действию
                интернет-пользователя. Традиционный лендинг описывает продукт,
                его преимущества и указывает на необходимость в приобретении
                этого продукта.
              </p>
              <div class="menu-content two">Корпоративный сайт</div>
              <p class="menu-content-hide two-hide">
                <span class="bold">Корпоративный сайт</span>-это многостраничный
                и многоуровневый сайт, где можно найти полную информацию о
                фирме, ее руководстве, продукции, истории. Корпоративные сайты
                привлекают новых клиентов и удерживают старых.
              </p>
              <div class="menu-content three">Сайт-визитка</div>
              <p class="menu-content-hide three-hide">
                <span class="bold">Сайт-визитка</span>-небольшой сайт, как
                правило, состоящий из пяти, семи веб-страниц и содержащий
                основную информацию об организации, частном лице, компании,
                товарах или услугах, прейскуранты, контактные данные.
              </p>
            </div>
          </div>
        </div>
        <div
          class="container menu--content link2 bgr-img-cover grid grid--menu"
          data-id="link2"
        >
          <div class="flex flex-menu">
            <h2 class="h2 h2-menu">Информационные порталы и блоги</h2>
            <p class="menu-p" data-id="1">
              Адаптивность на мобильных <br />устройствах
            </p>
            <p class="menu-p" data-id="1">
              Комфортная для чтения <br />
              типографика
            </p>
            <p class="menu-p" data-id="1">Удобная навигация по темам</p>
            <p class="menu-p" data-id="1">
              Возможность ведения блога в <br />
              открытом и закрытом режимах
            </p>
          </div>
        </div>
        <div
          class="container menu--content link3 bgr-img-cover grid grid--menu"
          data-id="link3"
        >
          <div class="flex flex-menu">
            <h2 class="h2 h2-menu">Приложения</h2>
            <p class="menu-p" data-id="2">Анализ рынка и целевой аудитории</p>
            <p class="menu-p" data-id="2">Исследование пути пользователя</p>
            <p class="menu-p" data-id="2">Создание стильного интерфейса</p>
            <p class="menu-p" data-id="2">
              Разработка удобных и быстрых <br />
              мобильных приложений
            </p>
          </div>
        </div>
        <div
          class="container menu--content link4 bgr-img-cover grid grid--menu"
          data-id="link4"
        >
          <div class="flex flex-menu">
            <h2 class="h2 h2-menu">UX/UI дизайн</h2>
            <p class="menu-p" data-id="3">Создание интерактивного прототипа</p>
            <p class="menu-p" data-id="3">Дизайн в современном стиле</p>
            <p class="menu-p" data-id="3">
              Разработка функционального <br />
              интерфейса
            </p>
            <p class="menu-p" data-id="3">Работа с цветом и типографикой</p>
            <p class="menu-p" data-id="3">Дизайн логотипов и визиток</p>
          </div>
        </div>
        <div class="menu--links accent-font">
          <div class="flex menu--link" id="link4" data-info="UX/UI дизайн">
            <p class="menu--link-p">UX/UI дизайн</p>
          </div>
          <div class="flex menu--link" id="link3" data-info="Приложения">
            <p class="menu--link-p">Приложения</p>
          </div>
          <div
            class="flex menu--link"
            id="link2"
            data-info="Информационные порталы и блоги"
          >
            <p class="menu--link-p">Информационные порталы и блоги</p>
          </div>
          <div
            class="flex menu--link menu--link--hide"
            id="link1"
            data-info="Сайты под ключ"
          >
            <p class="menu--link-p">Сайты под ключ</p>
          </div>
        </div>
      </div>
    </section>
    <!-- menu for tablet -->
    <section class="menu-tablet-section" id="menu">
      
      <div class="swiper mySwiperMenu">
        <div class="swiper-wrapper">
          <div class="flex flex-menu swiper-slide swiper-slide-menu link1">
            <h2 class="h2 h2-menu h2-menu-lineheight">Сайты под ключ</h2>
            <div class="flex flex-menu flex-menu-mobil">
              <p class="menu-p" data-id="0">Индивидуальная разработка сайта</p>
              <p class="menu-p" data-id="0">
                Адаптивные сайты на любых устройствах
              </p>
              <p class="menu-p" data-id="0">
                Исследование бизнеса, конкурентов и целевой аудитории
              </p>
              <p class="menu-p" data-id="0">
                Наполнение контентом (фото, товары, статьи и т.п.)
              </p>
              <div
                class="flex accent-font menu-accent-content menu-p"
                data-id="0"
              >
                <div class="menu-content one">Лендинг</div>
                <p class="menu-content-hide one-hide">
                  <span class="bold">Лендинг</span>-это особый тип сайтов,
                  оптимизированных для побуждения к действию
                  интернет-пользователя. Традиционный лендинг описывает продукт,
                  его преимущества и указывает на необходимость в приобретении
                  этого продукта.
                </p>
                <div class="menu-content two">Корпоративный сайт</div>
                <p class="menu-content-hide two-hide">
                  <span class="bold">Корпоративный сайт</span>-это
                  многостраничный и многоуровневый сайт, где можно найти полную
                  информацию о фирме, ее руководстве, продукции, истории.
                  Корпоративные сайты привлекают новых клиентов и удерживают
                  старых.
                </p>
                <div class="menu-content three">Сайт-визитка</div>
                <p class="menu-content-hide three-hide">
                  <span class="bold">Сайт-визитка</span>-небольшой сайт, как
                  правило, состоящий из пяти, семи веб-страниц и содержащий
                  основную информацию об организации, частном лице, компании,
                  товарах или услугах, прейскуранты, контактные данные.
                </p>
              </div>
            </div>
          </div>
          <div class="flex flex-menu swiper-slide swiper-slide-menu link2">
            <h2 class="h2 h2-menu h2-menu-lineheight">
              Информационные порталы и блоги
            </h2>
            <div class="flex flex-menu flex-menu-mobil">
              <p class="menu-p" data-id="1">
                Адаптивность на мобильных устройствах
              </p>
              <p class="menu-p" data-id="1">
                Комфортная для чтения типографика
              </p>
              <p class="menu-p" data-id="1">Удобная навигация по темам</p>
              <p class="menu-p" data-id="1">
                Возможность ведения блога в открытом и закрытом режимах
              </p>
            </div>
          </div>
          <div class="flex flex-menu swiper-slide swiper-slide-menu link3">
            <h2 class="h2 h2-menu h2-menu-lineheight">Приложения</h2>
            <div class="flex flex-menu flex-menu-mobil">
              <p class="menu-p" data-id="2">Анализ рынка и целевой аудитории</p>
              <p class="menu-p" data-id="2">Исследование пути пользователя</p>
              <p class="menu-p" data-id="2">Создание стильного интерфейса</p>
              <p class="menu-p" data-id="2">
                Разработка удобных и быстрых мобильных приложений
              </p>
            </div>
          </div>
          <div class="flex flex-menu swiper-slide swiper-slide-menu link4">
            <h2 class="h2 h2-menu h2-menu-lineheight">UX/UI дизайн</h2>
            <div class="flex flex-menu flex-menu-mobil">
              <p class="menu-p" data-id="3">
                Создание интерактивного прототипа
              </p>
              <p class="menu-p" data-id="3">Дизайн в современном стиле</p>
              <p class="menu-p" data-id="3">
                Разработка функционального интерфейса
              </p>
              <p class="menu-p" data-id="3">Работа с цветом и типографикой</p>
              <p class="menu-p" data-id="3">Дизайн логотипов и визиток</p>
            </div>
          </div>
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
      </div>
    </section>
    <h2 class="container h2 h2-section" id="projects">Наши проекты.</h2>
    <!-- project desctop -->
    <section class="project-desctop-section">
      <div class="grid-project grid--2-cols">
        <div class="project--block">
          <p class="menu-fonts project-text">Лэндинг для психолога</p>
          <img
            src="{% static 'img/macpro.png' %}"
            class="project-img"
            alt="landing"
          />
        </div>
        <div class="project--block">
          <p class="menu-fonts project-text">
            Онлайн платформа для IT-специалистов
          </p>
          <img
            src="{% static 'img/it-platform.png' %}"
            class="project-img"
            alt="it-platform"
          />
        </div>
      </div>
      <p class="h2-section hide-on-mobil">&nbsp;</p>
    </section>
    <!-- scroll project for tablet -->
    <section class="project-tablet-section" id="price">
      <div class="swiper mySwiperProjects">
        <div class="swiper-wrapper">
          <div class="project--block swiper-slide swiper-slide-project">
            <p class="menu-fonts project-text">Лэндинг для психолога</p>
            <img
              src="{% static 'img/macpro.png' %}"
              class="project-img-swiper-tablet"
              alt="landing"
            />
          </div>
          <div class="project--block swiper-slide swiper-slide-project">
            <p class="menu-fonts project-text">
              Онлайн платформа для IT-специалистов
            </p>
            <img
              src="{% static 'img/it-platform.png' %}"
              class="project-img-swiper-tablet"
              alt="it-platform"
            />
          </div>
        </div>
      </div>
      <p class="h2-section">&nbsp;</p>
    </section>
  </main>
  <div class="h2-section show-on-mobil">&nbsp;</div>

  {% include 'mainapp/includes/inc__footer.html' %}
</body>
{% endblock %}

mainapp/templates/mainapp/team.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block conteiner %}


    <body>

    {% include 'mainapp/includes/inc__header.html' %}

    <section class="team-desctop">
        <h2 class="container h2 h2-section">Наша команда.</h2>
        <div class="container grid grid--3-cols team">
            <div>
                <img src="{% static 'img/anna.jpg' %}" class="team-img" alt="Анна Подрезова"/>
                <p class="name">Анна Подрезова</p>
                <p class="profession">UX/UI дизайнер</p>
            </div>
            <div>
                <img src="{% static 'img/vasilij.jpg' %}" class="team-img" alt="Василий Щербатых"/>
                <p class="name">Василий Щербатых</p>
                <p class="profession">Backend разработчик</p>
            </div>
            <div>
                <img src="{% static 'img/tamara.jpg' %}" class="team-img" alt="Тамара Цэвээн"/>
                <p class="name">Тамара Цэвээн</p>
                <p class="profession">Frontend разработчик</p>
            </div>
        </div>
    </section>
    <section class="team-tablet">
        <h2 class="container h2 h2-section">Наша команда.</h2>
        <div class="swiper mySwiperTeam">
            <div class="swiper-wrapper">
                <div class="flex swiper-slide swiper-slide-team">
                    <img src="{% static 'img/anna.jpg' %}" alt="Анна Подрезова"/>
                    <div>
                        <p class="name">Анна Подрезова</p>
                        <p class="profession">UX/UI дизайнер</p>
                    </div>
                </div>
                <div class="flex swiper-slide swiper-slide-team">
                    <img src="{% static 'img/vasilij.jpg' %}" alt="Василий Щербатых"/>
                    <div>
                        <p class="name">Василий Щербатых</p>
                        <p class="profession">Backend разработчик</p>
                    </div>
                </div>
                <div class="flex swiper-slide swiper-slide-team">
                    <img src="{% static 'img/tamara.jpg' %}" alt="Тамара Цэвээн"/>
                    <div>
                        <p class="name">Тамара Цэвээн</p>
                        <p class="profession">Frontend разработчик</p>
                    </div>
                </div>
            </div>

        </div>
        <!-- </div> -->
    </section>

    {% include 'mainapp/includes/inc__footer.html' %}

    </body>
{% endblock %}